package main

import "fmt"
import "github.com/gin-gonic/gin"
import "log"
import "go-restapi/controllers/users"

func homePage (context *gin.Context) {
	context.JSON(200, gin.H{
		"message": "This is a home page generated by get.",
	})
}

func main() {
	fmt.Println("Hellow World JOpi")
	log.Println("Logging Logging....")
	r := gin.Default()
	r.GET("/", homePage)
	r.POST("/user/register", users.Register)
	r.Run()
}
