package main

import (
	"github.com/gin-gonic/gin"
	log "github.com/golang/glog"
	"go-restapi/controllers/users"
)

func homePage(context *gin.Context) {
	context.JSON(200, gin.H{
		"message": "This is a home page generated by get.",
	})
}

func main() {
	log.Info("Initializing Gin Services...")
	router := gin.Default()
	router.GET("/", homePage)
	router.POST("/user/register", users.Register)
	router.POST("/user/find", users.Find)
	router.POST("/user/find2", users.FindOnFile)
	router.Run()
}
